language: python
python:
  - 2.7
  - 3.3
  - 3.5
  - pypy
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
before_install:
  - export DJANGO_SETTINGS_MODULE=django_image_tools.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  - python manage.py migrate --noinput && coverage run --source=django_image_tools --omit=*django_migrations*,*admin* manage.py test django_image_tools
after_success:
  - coveralls
matrix:
  exclude:
    # Fails. Django issue
    # https://gist.github.com/thefourtheye/2205fe8ff7974e2cebf6
    - python: 3.5
      env: DJANGO=1.7
    # Deprecated version
    - python: 3.3
      env: DJANGO=1.8
      env: DJANGO=1.9
