language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
before_install:
  - export DJANGO_SETTINGS_MODULE=django_image_tools.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  - python manage.py migrate --noinput && coverage run --source=django_image_tools --omit=*django_migrations*,*admin* manage.py test django_image_tools
after_success:
  - coveralls
matrix:
  exclude:
    # Django doesn't support following combinations
    - python: 3.2
      env: DJANGO=1.4.0
    - python: 3.2
      env: DJANGO=1.4.5
    - python: 3.3
      env: DJANGO=1.4.0
    - python: 3.3
      env: DJANGO=1.4.5

    # Fails. Django issue #19944
    # https://code.djangoproject.com/ticket/19944
    - python: pypy
      env: DJANGO=1.5
